---
- name: Run Terraform
  terraform:
    project_path: "{{ playbook_dir }}/terraform"
    state: present
    workspace: default
    # Here we can override variables defined within the Terraform modules
    # Note that all variables that we want to override need to be present
    # in main.tf, even though they might be defined in a module
    # Needs ansible >2.10
    variables:
      network: "{{ network }}"
      keypair: "{{ keypair }}"
      private_key_path: "{{ private_key_path }}"
      cidr_ssh: "{{ cidr_ssh }}"
      cidr_list: "{{ cidr_list }}"
      control_port: "{{ control_port }}"
      flavor: "{{ flavor }}"
      image: "{{ image }}"
      mongodb_prefix: "{{ mongodb_prefix }}"
      ssh_user: "{{ ssh_user }}"
  register: tf_results

# Now iterate over the list returned by Terraform and build
# the inventory accordingly.
- name: Add entries to inventory
  add_host:
    name: "{{ item.name }}"
    ansible_ssh_host: "{{ item.ip }}"
    ansible_ssh_user: "{{item.ansible_ssh_user}}"
    ansible_ssh_private_key_file: "{{item.private_key_file}}"
    host_key_checking: no
    groups: "{{ item.groups }}"
    ansible_ssh_common_args: "{{item.ssh_args}}"
  loop: "{{ tf_results.outputs.inventory.value }}"


